_BASE_: aoa.yml

save_checkpoint_every: 3000
learning_rate: 0.00002
max_epochs: 40
learning_rate_decay_start: -1
scheduled_sampling_start: -1
reduce_on_plateau: true


train_sample_n: 5
self_critical_after: 0