_BASE_: aoa_ft_concat.yml

checkpoint_path: models/aoa_ft_concat_sc
start_from: models/aoa_ft_concat
save_checkpoint_every: 5000
learning_rate: 0.00002
max_epochs: 40
learning_rate_decay_start: -1
scheduled_sampling_start: -1
reduce_on_plateau: true


train_sample_n: 5
self_critical_after: 0
